import { useState, useCallback, useRef, useEffect } from "react";
import {
  Upload,
  X,
  Search,
  Heart,
  Shield,
  Droplet,
  Sun,
  Zap,
  Info,
  Clock,
  CheckCircle,
  Loader2,
} from "lucide-react";

import { jsPDF } from "jspdf";

const API_URL = "https://reyan03-plantreg-backend.hf.space/predict/";

const withBackoff = async (apiCall, maxRetries = 5) => {
  let delay = 1000;
  for (let i = 0; i < maxRetries; i++) {
    try {
      return await apiCall();
    } catch (error) {
      if (i === maxRetries - 1) {
        // If it's the last retry, throw the error
        throw new Error(`API call failed after ${maxRetries} retries.`);
      }
      // Retries are silent in the console
      await new Promise((resolve) => setTimeout(resolve, delay));
      delay *= 2; // Exponential increase
    }
  }
  // Fallback error, though should be caught inside the loop
  throw new Error("Exceeded maximum retries.");
};

// Result Display Component
const PredictionResult = ({ result }) => {
  if (!result || !result.prediction) return null;

  const {
    prediction,
    confidence,
    description,
    symptoms,
    prevention,
    treatment,
    fertilizer,
    soil,
  } = result;

  const isHealthy = prediction.toLowerCase().includes("healthy");

  const statusIcon = isHealthy ? (
    <CheckCircle className="status-icon success-color" />
  ) : (
    <X className="status-icon danger-color" />
  );

  const getIcon = (key) => {
    const baseClass = "detail-icon";
    switch (key) {
      case "description":
        return (
          <Info className={`${baseClass} `} style={{ color: "#51c951" }} />
        );
      case "symptoms":
        return (
          <Clock className={`${baseClass} `} style={{ color: "#c6c632" }} />
        );
      case "prevention":
        return (
          <Shield className={`${baseClass} `} style={{ color: "#0095ff" }} />
        );
      case "treatment":
        return <Heart className={`${baseClass} `} style={{ color: "red" }} />;
      case "fertilizer":
        return (
          <Droplet className={`${baseClass} `} style={{ color: "#de34de" }} />
        );
      case "soil":
        return <Sun className={`${baseClass} `} style={{ color: "orange" }} />;
      default:
        return <Zap className={`${baseClass} `} style={{ color: "grey" }} />;
    }
  };

  const infoSections = [
    { title: "Description", key: "description", content: description },
    { title: "Key Symptoms", key: "symptoms", content: symptoms },
    { title: "Prevention Tips", key: "prevention", content: prevention },
    { title: "Recommended Treatment", key: "treatment", content: treatment },
    { title: "Fertilizer Guidance", key: "fertilizer", content: fertilizer },
    { title: "Soil Conditions", key: "soil", content: soil },
  ];

  const generatePDF = () => {
    alert("File downloaded! Check your Downloads folder.");

    const doc = new jsPDF();
    const leftMargin = 15;
    const maxWidth = 180;
    const lineHeight = 8;
    let y = 25;

    // ---------- MAIN HEADER ----------
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.text("PlantReg Diagnostic Report", 105, 18, { align: "center" });

    y += lineHeight + 5;

    // ---------- DISEASE NAME ----------
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(`Detected Disease: ${prediction}`, leftMargin, y);
    y += lineHeight;

    // ---------- CONFIDENCE ----------
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.text(`Model Confidence: ${confidence}%`, leftMargin + 5, y);
    y += lineHeight + 6;

    // ---------- DETAILS ----------
    infoSections.forEach((s) => {
      // Page break
      if (y > 270) {
        doc.addPage();
        y = 20;
      }

      // Section title
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.text(s.title, leftMargin, y);
      y += lineHeight;

      // Section content
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      const wrappedText = doc.splitTextToSize(s.content, maxWidth);
      doc.text(wrappedText, leftMargin + 5, y);
      y += wrappedText.length * lineHeight + 6;
    });

    // ---------- FOOTER ----------
    doc.setFontSize(10);
    doc.setTextColor(120);
    doc.text(
      "Generated by PlantReg | AI-based Plant Disease Detection",
      105,
      290,
      { align: "center" }
    );

    doc.save("PlantReg_Report.pdf");
  };

  return (
    <div className="result-section">
      <h2 className="result-header">
        <Search className="result-header-icon" />
        Detailed Diagnostic Report
      </h2>

      <div
        className={`main-prediction-block ${
          isHealthy ? "healthy-block" : "diseased-block"
        }`}
      >
        <div className="prediction-status">
          {statusIcon}
          <div>
            <p className="status-label">Diagnosis Status:</p>
            <h3 className="status-prediction-text">{prediction}</h3>
          </div>
        </div>
        <div className="confidence-display">
          <p className="status-label">Model Confidence:</p>
          <p
            className={`confidence-value ${
              isHealthy ? "success-text" : "danger-text"
            }`}
          >
            {confidence}%
          </p>
        </div>
      </div>

      <div className="detail-grid">
        {infoSections.map((section) => (
          <div key={section.key} className="detail-card">
            <div className="detail-card-header">
              {getIcon(section.key)}
              <h4 className="detail-card-title">{section.title}</h4>
            </div>
            <p className="detail-card-content">{section.content}</p>
          </div>
        ))}
      </div>

      <div className="download-btn">
        <button className="downloader" onClick={generatePDF}>
          Generate-pdf
        </button>
      </div>
    </div>
  );
};

const Home = () => {
  // Ref for accessing the file input element directly
  const fileInputRef = useRef(null);

  const [selectedFile, setSelectedFile] = useState(null);
  const [previewUrl, setPreviewUrl] = useState("");
  const [predictionResult, setPredictionResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    const savedResult = localStorage.getItem("plantreg_result");
    const savedImage = localStorage.getItem("plantreg_image");

    if (savedResult && savedImage) {
      setPredictionResult(JSON.parse(savedResult));
      setPreviewUrl(savedImage);
    }
  }, []);

  loading
    ? (document.body.style.overflow = "hidden")
    : (document.body.style.overflow = "auto");

  // Handle file selection
  const handleFileChange = (e) => {
    const file = e.target.files[0];
    if (file && file.type.startsWith("image/")) {
      setSelectedFile(file);
      if (previewUrl) URL.revokeObjectURL(previewUrl);
      setPreviewUrl(URL.createObjectURL(file));
      setPredictionResult(null);
      setError("");
    } else {
      setSelectedFile(null);
      if (previewUrl) URL.revokeObjectURL(previewUrl);
      setPreviewUrl("");
      setError("File must be a valid image (PNG, JPG, JPEG).");
    }
  };

  const fileToBase64 = (file) =>
    new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => resolve(reader.result);
      reader.onerror = reject;
    });

  // Handle file removal
  const handleRemoveFile = useCallback(() => {
    setSelectedFile(null);
    if (previewUrl) URL.revokeObjectURL(previewUrl);
    setPreviewUrl("");
    setPredictionResult(null);
    setError("");
    // ✅ CLEAR STORAGE
    localStorage.removeItem("plantreg_result");
    localStorage.removeItem("plantreg_image");
  }, [previewUrl]);

  // Handle prediction submission
  const handlePrediction = async () => {
    if (!selectedFile) {
      setError("Please upload an image of a plant leaf first.");
      return;
    }

    setLoading(true);
    setError("");
    setPredictionResult(null);

    try {
      const formData = new FormData();
      formData.append("file", selectedFile);

      const apiCall = () =>
        fetch(API_URL, {
          method: "POST",
          body: formData,
        });

      const response = await withBackoff(apiCall);

      if (!response.ok) {
        throw new Error(`Server responded with status: ${response.status}`);
      }

      const data = await response.json();

      const formattedData = {
        ...data,
        confidence: parseFloat(data.confidence).toFixed(2),
      };

      // ✅ SAVE RESULT
      localStorage.setItem("plantreg_result", JSON.stringify(formattedData));

      // ✅ SAVE IMAGE
      const base64Image = await fileToBase64(selectedFile);
      localStorage.setItem("plantreg_image", base64Image);

      setPredictionResult(formattedData);
    } catch (err) {
      setError(
        `Prediction failed. Please ensure the backend server is running at ${API_URL}. ${err.message}`
      );
      setPredictionResult(null);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="app-container">
      {loading && (
        <div className="loading">
          <img src="./loader2.gif" />
        </div>
      )}
      <main id="detector" className="flex-grow pt-28 pb-16 max-w-7xl mx-auto">
        <div className="max-w-5xl mx-auto">
          {/* Header */}
          <div className="main-header mb-16">
            <p className="main-subtitle">AI-Powered Plant Health</p>
            <h1 className="main-title">
              <span className="main-title-green">Disease Diagnostics</span>
            </h1>
            <p className="main-description">
              Upload a high-resolution image of a leaf to receive a professional
              diagnosis and actionable advice in seconds.
            </p>
          </div>

          {/* Detection Card */}
          <div className="detection-card">
            <div className="detection-grid">
              <div className="upload-zone space-y-6">
                <h2 className="card-section-header">1. Upload Image</h2>

                <div className="preview-box">
                  {previewUrl ? (
                    <div className="preview-image-container">
                      <img
                        src={previewUrl}
                        alt="Leaf Preview"
                        className="preview-image"
                      />
                      <button
                        onClick={handleRemoveFile}
                        className="remove-button"
                        aria-label="Remove image"
                      >
                        <X className="w-4 h-4" />
                      </button>
                    </div>
                  ) : (
                    <label htmlFor="file-upload" className="file-label">
                      <Upload className="upload-icon" />
                      <p className="upload-text">Click to upload</p>
                      <p className="upload-subtext">
                        PNG, JPG, or JPEG up to 10MB
                      </p>
                      <input
                        id="file-upload"
                        name="file-upload"
                        type="file"
                        className="file-input"
                        accept="image/*"
                        onChange={handleFileChange}
                        ref={fileInputRef}
                      />
                    </label>
                  )}
                </div>
                {error && <p className="error-message">{error}</p>}
              </div>

              {/* Right Side: Analysis and Action (Col 3/5) */}
              <div className="analysis-zone space-y-6">
                <h2 className="card-section-header">2. Analyze & Results</h2>

                <div className="info-box">
                  <p className="info-text">
                    <Info className="info-icon" />
                    Please ensure the leaf is clearly visible and well-lit.
                  </p>
                </div>

                <button
                  onClick={handlePrediction}
                  disabled={!selectedFile || loading}
                  className="analyze-button"
                >
                  {loading ? (
                    <>
                      <Loader2 className="analyze-button-icon loading-icon" />
                      Running Deep Analysis...
                    </>
                  ) : (
                    <>
                      <Zap className="analyze-button-icon" />
                      Get Instant Diagnosis
                    </>
                  )}
                </button>

                {predictionResult && (
                  <div className="analysis-complete-box">
                    <p className="analysis-complete-text">
                      <CheckCircle className="analysis-complete-icon" />
                      Analysis Complete. Scroll down for the full report.
                    </p>
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Result Display */}
          <PredictionResult result={predictionResult} />

          {/* Placeholder for About Section */}
          <div id="info" className="about-section mt-20">
            <h2 className="about-header">How PlantReg Works</h2>
            <p className="about-text">
              PlantReg utilizes a MobileNetV2-based model trained on extensive
              datasets of common plant diseases. The system identifies visual
              patterns in the leaf structure and coloration to provide a
              diagnosis and confidence score. This quick, non-invasive method
              allows farmers and gardeners to respond rapidly, protecting crop
              yield.
            </p>
            <div className="about-stats">
              <div className="about-stat-group">
                <Shield className="about-stat-icon" />
                <p className="about-stat-label">Rapid Prevention</p>
              </div>
              <div className="about-stat-group">
                <Clock className="about-stat-icon text-yellow-600" />
                <p className="about-stat-label">24/7 Availability</p>
              </div>
              <div className="about-stat-group">
                <Heart className="about-stat-icon text-red-600" />
                <p className="about-stat-label">Actionable Treatments</p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
